db:
    image: itsalgeria/postgresql
    restart: always
    volumes:
        - ./pg_data:/var/lib/postgresql:rw
        - ./pg_hba.conf:/etc/postgresql/9.5/main/pg_hba.conf:rw
    ports:
        - "5432:5432"
insidjam:
    image: itsalgeria/insidjam
    restart: always
    command: start
    ports:
        - "8069:8069"
        - "8072:8072"
    links:
        - db:db
    volumes:
        - ./insidjam_data:/opt/odoo/data:rw
        - ./additional_addons:/opt/odoo/additional_addons:rw
        - ./odoo:/opt/odoo/sources/odoo:rw
        - ./insidjam.conf:/opt/odoo/etc/odoo.conf:rw
        - ./odoo.log:/opt/odoo/etc/odoo.log:rw
        - ./backups:/opt/insidjam/backups:rw

